---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: tokenadmin-mongo
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels: 
                name: tokenadmin-mongo
        spec:
            containers:
                - name: tokenadmin-mongo
                  image: mongo:4
                  ports:
                      - containerPort: 27017
                  env:
                  - name: MONGO_INITDB_ROOT_USERNAME
                    value: test
                  - name: MONGO_INITDB_ROOT_PASSWORD
                    value: test
---
apiVersion: v1
kind: Service
metadata:
    name: tokenadmin-mongo
    labels:
        name: tokenadmin-mongo
spec:
  ports:
  - port:       27017
    targetPort: 27017
  selector:
    name: tokenadmin-mongo
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: tokenadmin-api
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels: 
                name: tokenadmin-api
        spec:
            containers:
                - name: tokenadmin-api
                  image: registry.tokenadmin.work/jpw/tokenadmin-api:${BUILD_NUMBER}
                  ports:
                      - containerPort: 8080
                  env:
                  - name: MONGO_USERNAME
                    value: test
                  - name: MONGO_PASSWORD
                    value: test
                  - name: MONGO_HOST
                    value: tokenadmin-mongo
                  - name: MONGO_PORT
                    value: 27017
            imagePullSecrets:
                - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
    name: tokenadmin-api
    labels:
        name: tokenadmin-api
spec:
  ports:
  - port:       80
    targetPort: 3000
  selector:
    name: tokenadmin-api
  type: ClusterIP
