---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: tokenadmin-mongo
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels: 
                name: tokenadmin-mongo
        spec:
            containers:
                - name: tokenadmin-mongo
                  image: mongo:4
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        value: test
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        value: test
---
apiVersion: v1
kind: Service
metadata:
    name: tokenadmin-mongo
    labels:
        name: tokenadmin-mongo
spec:
  ports:
  - port:       27017
    targetPort: 27017
  selector:
    name: tokenadmin-mongo
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: tokenadmin-api
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels: 
                name: tokenadmin-api
        spec:
            containers:
                - name: tokenadmin-api
                  image: registry.trustfeed.io/jpw/tokenadmin-api:${BUILD_NUMBER}
                  ports:
                      - containerPort: 8080
                  env:
                      - name: MONGO_USERNAME
                        value: test
                      - name: MONGO_PASSWORD
                        value: test
                      - name: MONGO_HOST
                        value: tokenadmin-mongo
                      - name: MONGO_PORT
                        value: 27017
                      - name: TRUSTFEED_ADDRESS
                        value: 0x3aa9ce734dd21fa5e6962978e2ccc7f4ac513348
                      - name: RINKEBY_LIGHT_NODE
                        value: ws://10.240.63.49:8546
                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                          secretKeyRef:
                                  name: aws-s3
                                  key: access-key-id
                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                          secretKeyRef:
                                  name: aws-s3
                                  key: secret-access-key
                      - name: AWS_REGION
                        valueFrom:
                          secretKeyRef:
                                  name: aws-s3
                                  key: region
                      - name: INFURA_KEY
                        valueFrom:
                          secretKeyRef:
                                  name: infura
                                  key: key
            imagePullSecrets:
                - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
    name: tokenadmin-api
    labels:
        name: tokenadmin-api
spec:
  ports:
  - port:       80
    targetPort: 8080
  selector:
    name: tokenadmin-api
  type: ClusterIP
